### ISSUE TITLE
Example project compilation error

### ISSUE THREAD

**Issue by sidan5** [Ezaldeen99/BackgroundRemoval#11]
![Screenshot 2023-09-03 at 14 00 17](https://github.com/Ezaldeen99/BackgroundRemoval/assets/1595490/d1681a9d-04d0-473d-8166-48c8800924a6)

**Comment by Didami** [comment]
Issue #8 led to #10. @Ezaldeen99 merged pull request, but didn't update the example. These changes were meant to make optional unwrapping safer. The only missing parts in the example are the `do`, `try`, and `catch` statements. Replace them with the following code:

```
let image = UIImage(named: "child")
inputImage.image = image

let backgroundRemoval = BackgroundRemoval()
do {
    outputImage.image = try backgroundRemoval.removeBackground(image: image!)
    segmentedImage.image = try backgroundRemoval.removeBackground(image: image!, maskOnly: true)
} catch {
    print(error)
}
```
