### ISSUE TITLE
output image is not being saved in the iphone gallary

### ISSUE THREAD

**Issue by mobileexpert1** [Ezaldeen99/BackgroundRemoval#13]
When  i am saving the output image into the phone's album  it is saving the original image. Image with the background. Can you please check this ?

**Comment by aswar-company** [comment]
this looks like a duplicate for #2 please check the solution there, reopen the issue if this did not help you

**Comment by Ezaldeen99** [comment]
This looks like a duplicate to #2 , reopen the issue if the solution is not working
