### ISSUE TITLE
SPM Broken

### ISSUE THREAD

**Issue by cerupcat** [Ezaldeen99/BackgroundRemoval#7]
When trying to install via SPM, it gives an error that it can't resolve the package.

**Comment by Ezaldeen99** [comment]
You install it from Github URL directly using Apple swift packages installer, please let me know if this is enough or something else is needed

<img width="801" alt="Screen Shot 2023-01-15 at 12 50 01 PM" src="https://user-images.githubusercontent.com/30810111/212539046-f6606385-8313-42d6-bacf-f7d74829deb6.png">

**Comment by cerupcat** [comment]
Apologies, it was an error on my side.
